### ISSUE TITLE
Erro no script.js 

### ISSUE THREAD

**Issue by 97revenge** [97revenge/bootstrap-pagina-admin#2]
_nao estou conseguindo trabalhar a linha de código js na classe side-dropdown_

```
#sidebar .side-dropdown {
    padding-left: 48px;
    max-height: 0;
    overflow-y: hidden;
    transition: all 15s ease;
}

#sidebar .side-dropdown.show {
    max-height: 1000px;
}

#sidebar .side-dropdown a:hover {
    color: var(--azul);
}

```

nao está interagindo com o script.js

**Comment by marciomrb** [comment]
o erro não ta ai, ta no script / html
nos a, adicione a class = 'dropdown-item'

var button = document.querySelectorAll('a.dropdown-item');

button.forEach(function(button) {
    button.addEventListener('click', function() {
        var dropdown = this.nextElementSibling;
        if (dropdown.classList.contains('show')) {
            dropdown.classList.remove('show');
            dropdown.classList.remove('active');
        }
        else {
            dropdown.classList.add('show');
            dropdown.classList.add('active');
        }
    });
});

aqui funcionou

**Comment by 97revenge** [comment]
_Obrigado !_
